[package]
name = "read_file_data"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0.17"
reqwest = { version = "0.10", features = ["blocking", "json"] }
log = "0.4.14"

